spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&&serverTimezone=UTC&&useSSL=false&&useAffectedRows=true
    username: root
    password: dandan0000
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    default-statement-timeout: 30
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dandan.*

logging:
  file:
    path: 'C:\Users\28798\Desktop\毕设\shop\shopapi\'
    name: shop.log
  level:
    root: info